# Generated by Django 3.0.3 on 2020-02-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('pistol', 'Pistol'), ('shotgun', 'Shotgun'), ('rifle', 'Rifle'), ('heavy gun', 'Heavy Gun'), ('melee', 'Melee'), ('thrown', 'Thrown')], max_length=32)),
                ('ammo', models.CharField(choices=[('none', 'None'), ('5mm', '5mm'), ('10mm', '10mm')], max_length=32)),
                ('energy', models.BooleanField(default=False)),
                ('strength_factor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('level', models.PositiveSmallIntegerField()),
                ('damage', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
