# Generated by Django 3.0.2 on 2020-01-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('automatic pistol', 'Automatic Pistol'), ('non-automatic pistol', 'Non-Automatic Pistol'), ('shotgun', 'Shotgun'), ('automatic rifle', 'Automatic Rifle'), ('non-automatic rifle', 'Non-Automatic Rifle'), ('non-explosive heavy gun', 'Non-Explosive Heavy Gun'), ('explosive heavy gun', 'Explosive Heavy Gun'), ('one-handed melee', 'One-Handed Melee'), ('two-handed melee', 'Two-Handed Melee')], max_length=32)),
                ('energy', models.BooleanField(default=False)),
                ('strength_factor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('level', models.PositiveSmallIntegerField()),
                ('damage', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
