# Generated by Django 3.0.3 on 2020-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='energy',
        ),
        migrations.AddField(
            model_name='weapon',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weapon',
            name='explosive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ammo',
            field=models.CharField(choices=[('none', 'None'), ('.308', '.308'), ('.38', '.38'), ('.44', '.44'), ('.45', '.45'), ('.50 ball', '.50 ball'), ('.50', '.50'), ('10mm', '10mm'), ('5.56mm', '5.56mm'), ('5mm', '5mm'), ('cannonball', 'Cannonball'), ('railway spike', 'Railway Spike'), ('shotgun shell', 'Shotgun Shell'), ('2mm ec', '2mm EC'), ('alien blaster', 'Alien Blaster'), ('cryo cell', 'Cryo Cell'), ('fuel', 'Fuel'), ('fusion cell', 'Fusion Cell'), ('fusion core', 'Fusion Core'), ('gamma', 'Gamma'), ('plasma cartridge', 'Plasma Cartridge'), ('plasma core', 'Plasma Core'), ('40mm grenade', '40mm Grenade'), ('mini nuke', 'Mini Nuke'), ('missile', 'Missile')], max_length=32),
        ),
    ]
