# Generated by Django 3.0.3 on 2020-02-09 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damage', '0003_auto_20200208_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='accuracy',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='range',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=4),
            preserve_default=False,
        ),
    ]
