# Generated by Django 3.0.3 on 2020-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('coord_x', models.IntegerField()),
                ('coord_y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='location',
            field=models.ManyToManyField(to='shopper.Location'),
        ),
    ]
