# Generated by Django 3.0.3 on 2020-02-14 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0003_auto_20200214_1532'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='RecipeIngredient',
        ),
    ]
