# Generated by Django 3.0.3 on 2020-02-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper', '0004_auto_20200214_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='level',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
    ]
